# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: "us-central1-docker.pkg.dev/robotic-weft-462808-a2/k8s-learn"
  tag: "v1.0.5-2d9ede7"
  arch: amd64
  name: "kbot"
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
