# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: "tovmariupol"
  tag: "v1.0.5-19b12d9-amd64-0462e76"
  arch: amd64
  name: "kbot"
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
