name: KBOT-CICD

on: 
  push:
    branches:
      - develop
 
jobs:

  ci:
    name: CI
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Run test
        run:  make test

      - name: Authenticate to Google Cloud
        env:
          ACTIONS_RUNNER_DEBUG: true  # Enable debug logging for the action 
          ACTIONS_STEP_DEBUG: true    # Enable debug logging for the step
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}


      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: "us-central1-docker.pkg.dev/robotic-weft-462808-a2/k8s-learn"
        run: make image push
        
  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get Version
        run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Change Helm Values
        uses:  mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION)'  helm/values.yaml
        
      - name:  Git configuration
        run: |
          git config user.name github-actions 
          git config user.email github-actions@github.com
          git commit -am "Update version to $VERSION" 
          git push origin HEAD:main



  