name: KBOT-CICD

on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Run test
        run:  make test
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME  }}
        run: make image push
  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get Version
        run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV


      - name: Change Helm Values
        uses:  mikefarh/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION)'  helm/values.yaml
        
      - name:  Git configuration
        run: |
          git config user.name github-actions 
          git config user.email github-actions@github.com
          git commit -am "Update version to $VERSION" 
          git push origin HEAD:main



  